version: '3.3'

services:
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "${FRONTEND_ADDRESS}:3006"

  backend:
    env_file:
      # contains QDRANT_CLUSTER_URL and QDRANT_CLUSTER_TOKEN
      - secrets.env
      - .env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "${SERVICE_ADDRESS}:8000"
#for execution: $> sudo docker compose up
